require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

platform :ios, '10.0'
pod 'Firebase/Analytics'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

target 'Meme_Feed' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Meme_FeedTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    
  end
end

target 'Meme_Feed-tvOS' do
  # Pods for Meme_Feed-tvOS

  target 'Meme_Feed-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
